/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.spec.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  clearMocks: true,
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  collectCoverageFrom: [
    'src/common/file-upload/**/*.ts',
    '!src/common/file-upload/**/*.spec.ts',
    '!src/common/file-upload/**/*.interface.ts',
    'src/common/decorators/**/*.ts',
    '!src/common/decorators/**/*.spec.ts',
    'src/common/graylog/**/*.ts',
    '!src/common/graylog/**/*.spec.ts',
    'src/common/graphql/**/*.ts',
    '!src/common/graphql/**/*.spec.ts',
    'src/common/cache/**/*.ts',
    '!src/common/cache/**/*.spec.ts',
    'src/common/websocket/**/*.ts',
    '!src/common/websocket/**/*.spec.ts',
    '!src/common/websocket/**/*.interface.ts',
    'src/common/security/**/*.ts',
    '!src/common/security/**/*.spec.ts',
    '!src/common/security/**/*.interface.ts',
    'src/common/crypto/**/*.ts',
    '!src/common/crypto/**/*.spec.ts',
    'src/config/**/*.ts',
    '!src/config/**/*.spec.ts',
    'src/modules/whatsapp/**/*.ts',
    '!src/modules/whatsapp/**/*.spec.ts',
    'src/modules/websocket-example/**/*.ts',
    '!src/modules/websocket-example/**/*.spec.ts',
    'src/modules/health/**/*.ts',
    '!src/modules/health/**/*.spec.ts',
    'src/modules/email/**/*.ts',
    '!src/modules/email/**/*.spec.ts',
    'src/modules/users/**/*.ts',
    '!src/modules/users/**/*.spec.ts',
    '!src/modules/users/**/*.interface.ts',
    'src/modules/auth/**/*.ts',
    '!src/modules/auth/**/*.spec.ts',
    'src/wiki/**/*.ts',
    '!src/wiki/**/*.spec.ts',
  ],
  moduleNameMapper: {
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
  },
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: {
          rootDir: '.',
          esModuleInterop: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          strict: true,
          skipLibCheck: true,
          types: ['node', 'jest'],
        },
      },
    ],
  },
};
